name: Build and Deploy .NET + Angular App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Angular frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Angular
      working-directory: ClientApp
      run: |
        npm install
        npm run build --prod

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Restore and publish .NET backend
    - name: Restore .NET dependencies
      run: dotnet restore OrderAppDemo.Server.csproj

    - name: Publish .NET backend
      run: dotnet publish OrderAppDemo.Server.csproj -c Release -o publish

    # Deploy to Azure App Service
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "saorder"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish/wwwroot