name: Build and Deploy .NET + Angular App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build Angular
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Angular
      working-directory: OrderAppDemo.Server/ClientApp
      run: |
        npm install
        npm run build --prod

    # Build .NET API
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET dependencies
      run: dotnet restore OrderAppDemo.Server/OrderAppDemo.Server.csproj

    - name: Publish API
      run: dotnet publish OrderAppDemo.Server/OrderAppDemo.Server.csproj -c Release -o publish

    # Deploy to Azure App Service
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "saorder"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish